-- ============================================================
--  Waterproofing+  ·  Supabase database setup
--  HOW TO USE: In Supabase, open  SQL Editor -> New query,
--  paste this ENTIRE file, and click  Run.  Safe to re-run.
-- ============================================================

create table if not exists services (
  id text primary key, name text, sort int
);
create table if not exists materials (
  id text primary key, name text, category text, unit text, step numeric default 1,
  pack text, units_per_pallet numeric default 0, unit_cost numeric default 0,
  on_hand numeric default 0, reorder_at numeric default 0, location text
);
create table if not exists tools (
  id text primary key, name text, service text, battery boolean default false,
  status text default 'in', condition text default 'good', last_charged timestamptz,
  out_by text, out_job text, out_service text, notes text
);
create table if not exists trucks (
  id text primary key, name text, km numeric default 0, last_serviced date, last_oil_km numeric
);
create table if not exists truck_tasks (
  id text primary key, task text, service text, freq text default 'daily'
);
create table if not exists jobs (
  id text primary key, name text, client text, address text, active boolean default true
);
create table if not exists crew (
  id text primary key, name text, email text, points int default 0
);
create table if not exists material_log (
  id bigint generated by default as identity primary key, ts timestamptz default now(),
  material_id text, qty numeric, action text, job_id text, service text, crew_id text, note text
);
create table if not exists tool_log (
  id bigint generated by default as identity primary key, ts timestamptz default now(),
  tool_id text, action text, job_id text, service text, crew_id text, note text
);
create table if not exists truck_logs (
  id bigint generated by default as identity primary key, ts timestamptz default now(),
  truck_id text, km numeric, driver text, job_id text, service text, oil boolean, fuel boolean, repairs text
);
create table if not exists task_completions (
  crew_id text, task_id text, period_key text, done_at timestamptz default now(),
  primary key (crew_id, task_id)
);

-- Atomic material logging: records the entry AND adjusts stock in one safe step
-- (prevents two crew members from overwriting each other's counts).
create or replace function log_material(
  p_material_id text, p_qty numeric, p_action text, p_job_id text,
  p_service text, p_crew_id text, p_note text, p_delta numeric
) returns numeric as $$
declare new_qty numeric;
begin
  insert into material_log(material_id,qty,action,job_id,service,crew_id,note)
  values (p_material_id,p_qty,p_action,p_job_id,p_service,p_crew_id,p_note);
  update materials set on_hand = greatest(0, on_hand + p_delta)
  where id = p_material_id returning on_hand into new_qty;
  return new_qty;
end; $$ language plpgsql;


-- Seed data (only inserts if not already present) --
insert into services(id,name,sort) values('wp','Waterproofing',1) on conflict (id) do nothing;
insert into services(id,name,sort) values('ins','Insulation',2) on conflict (id) do nothing;
insert into services(id,name,sort) values('inj','Crack Injection',3) on conflict (id) do nothing;
insert into services(id,name,sort) values('trf','Traffic Coatings',4) on conflict (id) do nothing;
insert into services(id,name,sort) values('veh','Vehicle / General',5) on conflict (id) do nothing;

insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m1','Tremproof 260 (TP260)','wp','barrel',0.5,'52 gal drum · 4/pallet',4,905.56,6,6,'Yard') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m2','Tremproof Amphibia (blindside)','wp','roll',0.5,'5.91''×65.62'' · 20/pallet',20,1460,9,8,'Rack A') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m3','BSWV Membrane','wp','roll',0.5,'blind wall rolls',0,0,5,6,'Rack A') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m4','Vulkem 350 SL','wp','pail',1,'36 pails/pallet',36,0,7,6,'Shelf B') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m5','Vulkem 360 SL','wp','pail',1,'36 pails/pallet',36,0,12,8,'Shelf B') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m6','Vulkem 950 NF','wp','pail',1,'36 pails/pallet',36,0,6,6,'Shelf B') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m7','Vulkem 951 NF','wp','pail',1,'36 pails/pallet',36,0,4,4,'Shelf B') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m8','191 Primer','wp','pail',1,'',0,0,8,6,'Shelf B') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m9','Watchdog Waterproofing','wp','pail',1,'Gablecraft',0,0,5,4,'Shelf C') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m10','Tremdrain 6000 (conventional)','drn','roll',0.5,'6''×50'' · 8/pallet',8,180,16,12,'Rack D') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m11','Tremdrain 6000x (blind wall)','drn','roll',0.5,'8/pallet',8,264.26,3,6,'Rack D') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m12','Tremco Drainstar (dimple)','drn','roll',0.5,'300 sq ft/roll',0,0,31,20,'Rack D') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m13','NaturaSeal Drainmat (backup)','drn','roll',0.5,'',0,0,10,6,'Rack D') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m14','Soprema G10 Drainmat','drn','roll',0.5,'',0,0,4,4,'Rack D') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m15','Delta MS Drainmat','drn','roll',0.5,'Gablecraft',0,0,6,4,'Rack D') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m16','Warm & Dri Board','drn','board',1,'',0,0,40,24,'Rack E') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m17','Drain Boots','drn','boot',1,'',0,0,60,40,'Bin E2') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m18','Dymonic 100 (Black)','clk','tube',1,'15/case · 66 cases/pallet',990,8.67,45,30,'Shelf F') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m19','Dymonic 100 FC (White)','clk','tube',1,'15/case',0,0,30,30,'Shelf F') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m20','Dow CWS (White)','clk','sausage',1,'EllisDon',0,0,24,15,'Shelf F') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m21','Dow CWS (Grey)','clk','sausage',1,'AssaAbloy',0,0,12,15,'Shelf F') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m22','Pekora Dynafex','clk','sausage',1,'',0,0,18,12,'Shelf F') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m23','Backer Rod','clk','roll',1,'',0,0,8,6,'Shelf F') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m24','XPS 2" Insulation','ins','sheet',1,'',0,0,24,20,'Rack G') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m25','CFI 2" Panel','ins','panel',1,'',0,0,30,20,'Rack G') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m26','CFI 4" Panel','ins','panel',1,'',0,0,12,12,'Rack G') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m27','PL300 CFI Glue','ins','tube',1,'',0,0,20,12,'Shelf H') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m28','Injection Ports','inj','each',1,'',0,0,200,100,'Bin I1') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m29','Injection Resin','inj','litre',0.5,'',0,0,24,15,'Shelf I') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m30','Accelerator / Catalyst','inj','cup',1,'',0,0,18,12,'Shelf I') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m31','Xypex Patch & Plug','inj','lb',1,'',0,0,25,20,'Shelf I') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m32','Xypex Concentrate','inj','lb',1,'',0,0,20,15,'Shelf I') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m33','Kryton T1','inj','gallon',0.5,'',0,0,6,4,'Shelf I') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m34','Vulkem 346 TC','trf','pail',1,'',0,0,7,6,'Shelf J') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m35','Alsan Traffic Coating','trf','gallon',0.5,'',0,0,5,4,'Shelf J') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m36','16-Grit Sand','trf','bag',1,'',0,0,20,15,'Yard') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m37','Term Bar','acc','unit',1,'33/case',0,0,90,60,'Rack K') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m38','Universal T','acc','unit',1,'10/case',0,26.32,60,40,'Rack K') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m39','UCAN Shot Nails/Pins','acc','each',1,'100/case',0,0,1200,800,'Bin K2') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m40','Fender Washers','acc','each',1,'',0,0,600,400,'Bin K3') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m41','BG Grip Tape 6"×75''','con','roll',1,'8/case',0,42.6,24,16,'Shelf L') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m42','White Rags','con','bag',1,'',0,0,10,8,'Shelf L') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m43','Roller Sleeves','con','each',1,'',0,0,24,20,'Shelf L') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m44','Propane 20 lb','con','tank',1,'',0,0,4,3,'Yard') on conflict (id) do nothing;
insert into materials(id,name,category,unit,step,pack,units_per_pallet,unit_cost,on_hand,reorder_at,location) values('m45','Xylene','con','gallon',0.5,'',0,0,6,4,'Flammables') on conflict (id) do nothing;

insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t1','Propane Torch Kit','wp',false,'in','good',null,null,null,null,null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t2','Hot Air Welder','wp',false,'out','good',null,'c1','s1','wp',null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t3','Seam Roller Set','wp',false,'in','good',null,null,null,null,null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t4','Cordless Impact Driver','ins',true,'in','good',now() - interval '0 days',null,null,null,null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t5','Hot Knife','ins',false,'in','repair',null,null,null,null,'Element intermittent') on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t6','Foam Applicator Gun','ins',false,'in','good',null,null,null,null,null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t7','Injection Pump','inj',false,'out','good',null,'c0','s5','inj',null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t8','Cordless Hammer Drill','inj',true,'out','good',now() - interval '1 days','c0','s5','inj',null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t9','Airless Sprayer','trf',false,'in','damaged',null,null,null,null,'Tip guard cracked') on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t10','Cordless Angle Grinder','trf',true,'in','good',now() - interval '3 days',null,null,null,null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t11','Spike Shoes (pair)','trf',false,'in','good',null,null,null,null,null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t12','Generator 3500W','veh',false,'in','good',null,null,null,null,null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t13','Pressure Washer','veh',false,'in','good',null,null,null,null,null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t14','Cordless Drill #1','veh',true,'in','good',now() - interval '0 days',null,null,null,null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t15','Cordless Drill #2','veh',true,'out','good',now() - interval '2 days','c1','s1','wp',null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t16','LED Work Lights','veh',true,'in','good',now() - interval '4 days',null,null,null,null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t17','Extension Ladder 24''','veh',false,'in','good',null,null,null,null,null) on conflict (id) do nothing;
insert into tools(id,name,service,battery,status,condition,last_charged,out_by,out_job,out_service,notes) values('t18','Wet/Dry Vac','veh',false,'in','good',null,null,null,null,null) on conflict (id) do nothing;

insert into trucks(id,name,km,last_serviced,last_oil_km) values('tr1','Truck 1 — Ford F-350',184250,'2026-06-20',184000) on conflict (id) do nothing;
insert into trucks(id,name,km,last_serviced,last_oil_km) values('tr2','Truck 2 — RAM 2500',97430,'2026-05-02',96800) on conflict (id) do nothing;
insert into trucks(id,name,km,last_serviced,last_oil_km) values('tr3','Van 3 — Transit',61200,'2026-07-01',60900) on conflict (id) do nothing;

insert into truck_tasks(id,task,service,freq) values('k1','Check oil level','veh','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k2','Top up fuel for tomorrow','veh','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k3','Record odometer / KM','veh','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k4','Tire pressure & lights walk-around','veh','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k5','Coolant & washer fluid check','veh','weekly') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k6','Wash truck','veh','weekly') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k7','Oil-change / service due check','veh','monthly') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k8','Fire extinguisher & first-aid check','veh','monthly') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k9','Load membranes & primers per job list','wp','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k10','Secure Tremproof barrels / Vulkem pails','wp','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k11','Torch, propane & rollers loaded','wp','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k12','Load CFI / XPS panels per job','ins','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k13','PL glue, fasteners & drill bits loaded','ins','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k14','Load injection pump, ports & resin','inj','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k15','Xypex / Kryton & catalyst loaded','inj','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k16','Load Vulkem / Alsan & sand','trf','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k17','Sprayer, spike shoes & rollers loaded','trf','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k18','Log all materials used / delivered','veh','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k19','Return unused materials to warehouse','veh','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k20','Check in tools & put cordless on charge','veh','daily') on conflict (id) do nothing;
insert into truck_tasks(id,task,service,freq) values('k21','Note repairs needed & lock up','veh','daily') on conflict (id) do nothing;

insert into jobs(id,name,client,address,active) values('s1','Blackcrete — 814 Hockley Ave','Blackcrete','814 Hockley Ave',true) on conflict (id) do nothing;
insert into jobs(id,name,client,address,active) values('s2','EllisDon — Cow Bay Hospital','EllisDon','6775 Bell McKinnon Rd',true) on conflict (id) do nothing;
insert into jobs(id,name,client,address,active) values('s3','ARYZE — 450 Dallas Rd','ARYZE','450 Dallas Rd',true) on conflict (id) do nothing;
insert into jobs(id,name,client,address,active) values('s4','Orion — Aura','Orion','875 Citation Road',true) on conflict (id) do nothing;
insert into jobs(id,name,client,address,active) values('s5','Spire — 2300 Douglas St','Spire','2300 Douglas Street',true) on conflict (id) do nothing;
insert into jobs(id,name,client,address,active) values('s6','IronClad — Bear Mountain','IronClad','2106 Bear Mtn Pkwy',true) on conflict (id) do nothing;

insert into crew(id,name,email,points) values('c0','You','',220) on conflict (id) do nothing;
insert into crew(id,name,email,points) values('c1','Mike R.','',410) on conflict (id) do nothing;
insert into crew(id,name,email,points) values('c2','Dave L.','',355) on conflict (id) do nothing;
insert into crew(id,name,email,points) values('c3','Sam T.','',180) on conflict (id) do nothing;
insert into crew(id,name,email,points) values('c4','Carlos M.','',290) on conflict (id) do nothing;

-- Turn on row-level security and allow the app's public key to read/write.
-- (This keeps Supabase happy now; we add proper crew logins later.)
alter table services enable row level security;
drop policy if exists "app access" on services;
create policy "app access" on services for all using (true) with check (true);
alter table materials enable row level security;
drop policy if exists "app access" on materials;
create policy "app access" on materials for all using (true) with check (true);
alter table tools enable row level security;
drop policy if exists "app access" on tools;
create policy "app access" on tools for all using (true) with check (true);
alter table trucks enable row level security;
drop policy if exists "app access" on trucks;
create policy "app access" on trucks for all using (true) with check (true);
alter table truck_tasks enable row level security;
drop policy if exists "app access" on truck_tasks;
create policy "app access" on truck_tasks for all using (true) with check (true);
alter table jobs enable row level security;
drop policy if exists "app access" on jobs;
create policy "app access" on jobs for all using (true) with check (true);
alter table crew enable row level security;
drop policy if exists "app access" on crew;
create policy "app access" on crew for all using (true) with check (true);
alter table material_log enable row level security;
drop policy if exists "app access" on material_log;
create policy "app access" on material_log for all using (true) with check (true);
alter table tool_log enable row level security;
drop policy if exists "app access" on tool_log;
create policy "app access" on tool_log for all using (true) with check (true);
alter table truck_logs enable row level security;
drop policy if exists "app access" on truck_logs;
create policy "app access" on truck_logs for all using (true) with check (true);
alter table task_completions enable row level security;
drop policy if exists "app access" on task_completions;
create policy "app access" on task_completions for all using (true) with check (true);

-- Done. You should see the tables under Table Editor, filled with your data.